### ISSUE TITLE
Unbound module `Ppx_show_runtime`

### ISSUE THREAD

**Issue by bluddy** [thierry-martinez/ppx_show#2]
I'm trying to switch away from `ppx_deriving.show` based on community guidelines. However, I get the error `unbound module Ppx_show_runtime`. My dune file is as follows:

```
(executable
  (public_name rails)
  (name main)
  (libraries iter containers containers-data gen imagelib imagelib.unix tsdl owl-base sexplib)
  (preprocess (staged_pps ppx_import ppx_deriving.show ppx_deriving.enum ppx_deriving.eq ppx_deriving.ord lens.ppx_deriving ppx_hash ppx_sexp_conv))
  (modes exe)
  )
(env
  (dev
    (flags (:standard -warn-error -A -w -30))))
```
and I get the error when trying to switch ppx_deriving.show with ppx_show.

**Comment by thierry-martinez** [comment]
Thank you for the report! And sorry for the delay. `ppx_show` generated code relies on the `ppx_show_runtime` library: you should add `ppx_show_runtime` in `(libraries ...)`: I just added a note in [README.md](https://github.com/thierry-martinez/ppx_show/blob/master/README.md) about this. Thank you again!

**Comment by tatchi** [comment]
I tried the same but without luck:

```bash
File "bin/dune", line 5, characters 19-35:
5 |  (libraries parser ppx_show_runtime))
                       ^^^^^^^^^^^^^^^^
Error: Library "ppx_show_runtime" not found.
```

I figured it should be `ppx_show.runtime` instead

**Comment by tatchi** [comment]
https://github.com/thierry-martinez/ppx_show/pull/3

**Comment by thierry-martinez** [comment]
Oh, sorry for the confusion, and thank you for the fix!
